Watching for file changes with StatReloader
Internal Server Error: /api/execute-news-gen-img
Traceback (most recent call last):
  File "C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\api\views.py", line 182, in post
    result = self.execute_news_gen_img(index)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NewsGenImgView' object has no attribute 'execute_news_gen_img'
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_service.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\api\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\api\views.py changed, reloading.
Watching for file changes with StatReloader
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
生成圖片失敗: 500 Server Error: Internal Server Error for url: https://cloud.leonardo.ai/api/rest/v1/generations
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
Watching for file changes with StatReloader
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
翻譯失敗: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 08242b06************************c303. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
翻譯失敗: name 'client' is not defined
翻譯失敗: name 'client' is not defined
翻譯失敗: name 'client' is not defined
翻譯失敗: name 'client' is not defined
翻譯失敗: name 'client' is not defined
翻譯失敗: name 'client' is not defined
翻譯失敗: name 'client' is not defined
翻譯失敗: name 'client' is not defined
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/execute-news-gen-img
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/execute-news-gen-img
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/execute-news-gen-img
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/execute-news-gen-img
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/execute-news-gen-img
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\api\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\api\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/execute-news-gen-img
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\api\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/execute-news-gen-img
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\api\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\news_storyboard\services\news_gen_img.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/execute-news-gen-img
Internal Server Error: /api/execute-news-gen-img
C:\Users\翁\Desktop\新聞台\server\PhoenEY_News_Server-new-\api\views.py changed, reloading.
Watching for file changes with StatReloader
生成圖片失敗: 403 Client Error: Forbidden for url: https://cloud.leonardo.ai/api/rest/v1/generations
